In [1]:
import pandas as pd

$$ odds = \frac{p}{1-p}$$

In [2]:
probabilities = [0.1, 0.3, 0.5, 0.7, 0.9]

odds_table = pd.DataFrame({
    "probability": probabilities
})

p = odds_table["probability"]

odds_table["odds"] = p/(1 - p)

odds_table

# Positive Relationship

# Negative Relationship

,probability,odds
0,0.1,0.111111
1,0.3,0.428571
2,0.5,1.000000
3,0.7,2.333333
4,0.9,9.000000


In [3]:
from math import log

In [4]:
log(p[0]/(1-p[0]))

-2.197224577336219

In [5]:
odds_table['log_ods'] = [log(i/(1-i)) for i in list(p)]

odds_table

,probability,odds,log_ods
0,0.1,0.111111,-2.197225
1,0.3,0.428571,-0.847298
2,0.5,1.000000,0.000000
3,0.7,2.333333,0.847298
4,0.9,9.000000,2.197225


In [6]:
import pandas as pd

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv("https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/regression/logistic_regression/synthetic_churn_data.csv")
print(f"Dataset shape: {df.shape}")
df.head()

Dataset shape: (1000, 6)


,tenure,monthly_charges,support_calls,contract_type,churn,education_level
0,29,46.867736,6,0,0,High School
1,15,74.163421,6,0,0,Bachelor
2,8,83.347822,3,1,0,Master
3,21,45.788769,2,0,0,High School
4,19,33.935607,7,0,1,Master


In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   tenure           1000 non-null   int64  
 1   monthly_charges  1000 non-null   float64
 2   support_calls    1000 non-null   int64  
 3   contract_type    1000 non-null   int64  
 4   churn            1000 non-null   int64  
 5   education_level  1000 non-null   str    
dtypes: float64(1), int64(4), str(1)
memory usage: 53.8 KB


In [8]:
df['churn'].value_counts(normalize=True)

churn
0    0.633
1    0.367
Name: proportion, dtype: float64

In [9]:
df['churn'].value_counts(normalize=False)

churn
0    633
1    367
Name: count, dtype: int64

In [10]:
df[['churn', 'contract_type']].value_counts()

churn  contract_type
0      1                347
       0                286
1      0                235
       1                132
Name: count, dtype: int64

In [11]:
churn_rate_by_contract = df.groupby('contract_type')['churn'].mean().reset_index()
import plotly.express as px
fig = px.bar(churn_rate_by_contract, x='contract_type', y='churn', title='Churn Rate by Contract Type')
fig.update_layout(
    xaxis_title='Contract Type (0 = Prepaid, 1 = Postpaid',
    yaxis_title='Churn Rate',
    template='plotly_white'
)   
fig.show()

In [12]:
churn_rate_by_education = df.groupby('education_level')['churn'].mean().reset_index()
import plotly.express as px
fig = px.bar(churn_rate_by_education, x='education_level', y='churn', title='Churn Rate by Education Level')
fig.update_layout(
    xaxis_title='Education Level',
    yaxis_title='Churn Rate',
    template='plotly_white'
)   
fig.show()

In [13]:
X = df.drop(columns=["churn"])
y = df["churn"]

In [14]:
X

,tenure,monthly_charges,support_calls,contract_type,education_level
0,29,46.867736,6,0,High School
1,15,74.163421,6,0,Bachelor
2,8,83.347822,3,1,Master
3,21,45.788769,2,0,High School
4,19,33.935607,7,0,Master
...,...,...,...,...,...
995,30,20.321826,6,0,High School
996,23,81.958934,3,1,Master
997,32,55.549301,8,0,PhD
998,17,99.419733,4,0,Master


In [15]:
education_order = ["High School", "Bachelor", "Master", "PhD"]

df["education_level"] = pd.Categorical(
    df["education_level"],
    categories=education_order,
    ordered=True
)

education_dummies = pd.get_dummies(
    df["education_level"],
    prefix="education",
    drop_first=True,
    dtype=int
)

education_dummies.head()

,education_Bachelor,education_Master,education_PhD
0,0,0,0
1,1,0,0
2,0,1,0
3,0,0,0
4,0,1,0


In [16]:
X_encoded = pd.concat([X,education_dummies],axis=1)
X_encoded.head()

,tenure,monthly_charges,support_calls,contract_type,education_level,education_Bachelor,education_Master,education_PhD
0,29,46.867736,6,0,High School,0,0,0
1,15,74.163421,6,0,Bachelor,1,0,0
2,8,83.347822,3,1,Master,0,1,0
3,21,45.788769,2,0,High School,0,0,0
4,19,33.935607,7,0,Master,0,1,0


In [17]:
X = X_encoded
#del X_encoded

In [18]:
def test():
    return ('X_train', 'X_test', 'y_train', 'y_test' )

In [19]:
x1, x2, x3, x4 = test()
print (x1)
print (x2)
print (x3)
print (x4)

X_train
X_test
y_train
y_test


In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
X_train.head()

,tenure,monthly_charges,support_calls,contract_type,education_level,education_Bachelor,education_Master,education_PhD
494,32,51.615610,6,0,Bachelor,1,0,0
687,26,52.433375,5,0,High School,0,0,0
720,31,32.771348,2,0,Bachelor,1,0,0
381,33,100.172808,0,0,Master,0,1,0
3,21,45.788769,2,0,High School,0,0,0


In [22]:
train_size = len(X_train)
test_size = len(X_test)

train_churn_rate = y_train.mean()
test_churn_rate = y_test.mean()

print("Training rows:", train_size)
print("Test rows:", test_size)
print("Training churn rate:", round(train_churn_rate, 3))
print("Test churn rate:", round(test_churn_rate, 3))

Training rows: 800
Test rows: 200
Training churn rate: 0.368
Test churn rate: 0.365


In [23]:
# for fixing the following model code error
X_train.select_dtypes(include="object").columns

C:\Users\Ani\AppData\Local\Temp\ipykernel_13020\258923943.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_train.select_dtypes(include="object").columns


Index(['education_level'], dtype='str')

In [24]:
# for fixing the following model code error
print(X_train.select_dtypes(include="object").columns)
print(X_train.select_dtypes(include="object").nunique())

Index(['education_level'], dtype='str')
education_level    4
dtype: int64


C:\Users\Ani\AppData\Local\Temp\ipykernel_13020\3790006109.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(X_train.select_dtypes(include="object").columns)
C:\Users\Ani\AppData\Local\Temp\ipykernel_13020\3790006109.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migr

In [25]:
# for fixing the following model code error
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

In [26]:
# for fixing the following model code error
X_train = pd.get_dummies(X_train, columns=["education_level"])
X_test = pd.get_dummies(X_test, columns=["education_level"])

In [27]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [28]:
probs = model.predict_proba(X_test)
# [1-p, p]
probs = probs[:,1]

In [29]:
threshold = 0.5
preds = (probs >= threshold).astype(int)
preds[:5]

array([0, 0, 0, 1, 0])

In [30]:
prediction_results = X_test.copy()
prediction_results['actual_churn'] = y_test.values
prediction_results['prediction_probs'] = probs
prediction_results['prediction_churn'] = preds

In [31]:
prediction_results.head()

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD,education_level_Bachelor,education_level_High School,education_level_Master,education_level_PhD,actual_churn,prediction_probs,prediction_churn
361,34,55.062693,2,1,0,0,0,False,True,False,False,0,0.016635,0
5,23,103.493024,4,0,0,0,1,False,False,False,True,0,0.417456,0
692,25,75.778342,5,0,0,1,0,False,False,True,False,1,0.475915,0
708,6,112.717782,5,1,0,1,0,False,False,True,False,0,0.615776,1
841,26,67.601813,7,1,0,0,1,False,False,False,True,0,0.320746,0


**Outcome	Meaning**
- **True Positive**	Customer churned and model predicted churn
- **False Positive**	Customer did not churn but model predicted churn
- **False Negative**	Customer churned but model missed it
- **True Negative**	Customer did not churn and model predicted no churn

In [37]:
prediction_results[['actual_churn','prediction_churn']].value_counts()

actual_churn  prediction_churn
0             0                   103
1             1                    50
0             1                    24
1             0                    23
Name: count, dtype: int64

In [35]:
cm = confusion_matrix(y_test, preds)

tn, fp, fn, tp = cm.ravel()

cm

array([[103,  24],
       [ 23,  50]])

In [53]:
accuracy = accuracy_score(y_test, preds) #(103+50)/200
precision = precision_score(y_test, preds) #50/(50+24)
recall = recall_score(y_test, preds) #50/(50+23)

print("Accuracy:", round(accuracy, 3))
print("Precision:", round(precision, 3))
print("Recall:", round(recall, 3))

Accuracy: 0.765
Precision: 0.676
Recall: 0.685


In [34]:
cm = confusion_matrix(y_test,preds,normalize='all')
cm

array([[0.515, 0.12 ],
       [0.115, 0.25 ]])

In [36]:
cm = confusion_matrix(y_test,preds,normalize='true')
cm

array([[0.81102362, 0.18897638],
       [0.31506849, 0.68493151]])

In [ ]:
retention_cost = 10
retention_benefit = 50 #COHORT Analysis

revenue_from_saved_customers = tp * (retention_benefit - retention_cost)
cost_from_unnecessary_contacts = fp * retention_cost

net_profit = revenue_from_saved_customers - cost_from_unnecessary_contacts

print("Revenue from saved customers:", revenue_from_saved_customers)
print("Cost from unnecessary contacts:", cost_from_unnecessary_contacts)
print("Net profit:", net_profit)

Revenue from saved customers: 2000
Cost from unnecessary contacts: 240
Net profit: 1760


In [55]:
prediction_results.head()

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD,education_level_Bachelor,education_level_High School,education_level_Master,education_level_PhD,actual_churn,prediction_probs,prediction_churn
361,34,55.062693,2,1,0,0,0,False,True,False,False,0,0.016635,0
5,23,103.493024,4,0,0,0,1,False,False,False,True,0,0.417456,0
692,25,75.778342,5,0,0,1,0,False,False,True,False,1,0.475915,0
708,6,112.717782,5,1,0,1,0,False,False,True,False,0,0.615776,1
841,26,67.601813,7,1,0,0,1,False,False,False,True,0,0.320746,0


In [58]:
prediction_results.sort_values(by='prediction_probs', ascending=False).head(50)

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD,education_level_Bachelor,education_level_High School,education_level_Master,education_level_PhD,actual_churn,prediction_probs,prediction_churn
120,2,43.295947,9,0,0,1,0,False,False,True,False,1,0.942094,1
456,9,116.941232,7,0,0,0,1,False,False,False,True,1,0.918212,1
291,20,88.049930,9,0,0,0,1,False,False,False,True,0,0.913930,1
409,9,85.032569,8,0,0,0,1,False,False,False,True,1,0.912133,1
59,16,69.549132,9,0,0,0,1,False,False,False,True,1,0.900990,1
103,9,102.891547,7,0,0,0,1,False,False,False,True,1,0.894109,1
42,17,76.640464,8,0,1,0,0,True,False,False,False,1,0.888878,1
869,1,28.479202,8,0,0,1,0,False,False,True,False,1,0.878189,1
638,29,102.261432,8,0,0,1,0,False,False,True,False,1,0.872779,1
45,6,113.682974,8,1,0,0,1,False,False,False,True,0,0.864915,1


In [60]:
model.coef_[0]
np.exp(model.coef_[0])

array([0.94629366, 1.02048337, 1.76591244, 0.29235903, 1.06651742,
       1.06085571, 0.89478229, 1.06651742, 0.98781625, 1.06085571,
       0.89478229])

In [65]:
coef_df = pd.DataFrame({
    "feature": X_train.columns,
    "beta": model.coef_[0],
    "exp_beta": np.exp(model.coef_[0])
})

coef_df = coef_df.sort_values("exp_beta", ascending=False)

coef_df

,feature,beta,exp_beta
2,support_calls,0.568668,1.765912
7,education_level_Bachelor,0.064399,1.066517
4,education_Bachelor,0.064399,1.066517
9,education_level_Master,0.059076,1.060856
5,education_Master,0.059076,1.060856
1,monthly_charges,0.020276,1.020483
8,education_level_High School,-0.012259,0.987816
0,tenure,-0.055202,0.946294
6,education_PhD,-0.111175,0.894782
10,education_level_PhD,-0.111175,0.894782
